Assignment_5/django_code/demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("myapp.urls"))
]

Assignment_5/django_code/myapp/urls.py
from django.urls import path
from . import views
from .views import  process_form, patient_list, medical_records_list, prediction_results_list


urlpatterns = [
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path("", views.process_form, name="process_form"),
    path('patients/', patient_list, name='patient_list'),
    path('medical_records/', medical_records_list, name='medical_records_list'),
    path('prediction_results/', views.prediction_results_list, name='prediction_results_list'),
    path('about/', views.about_page, name='about'),
    path('technical-support/', views.technical_support, name='technical_support')
]

Assignment_5/django_code/myapp/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Model for the Patient's personal info
class Patients(models.Model):
    patient_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length= 20)
    last_name = models.CharField(max_length=20)
    date_of_birth = models.DateField()
    sex = models.CharField(max_length=10)
    height = models.FloatField()
    weight = models.FloatField()
    blood_type = models.CharField(max_length=5)
    city = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    telephone_number = models.CharField(max_length=15)
    insurance_number = models.CharField(max_length=50)


# Model for the Records of the test which will be used for the prediction
class MedicalRecords(models.Model):

    SEX_CHOICES = [(0, 'Male'), (1, 'Female')]
    CP_CHOICES = [
        (0, 'Typical Angina'),
        (1, 'Atypical Angina'),
        (2, 'Non-anginal Pain'),
        (3, 'Asymptomatic')
    ]
    FASTING_CHOICES = [(0, 'False'), (1, 'True')]
    RESTECG_CHOICES = [
        (0, 'Normal'),
        (1, 'Having ST-T wave abnormality'),
        (2, 'Probable or definite left ventricular hypertrophy')
    ]
    EXE_ANGINA_CHOICES = [(0, 'No'), (1, 'Yes')]
    SLOPE_CHOICES = [(0, 'Upsloping'), (1, 'Flat'), (2, 'Downsloping')]
    VESSELS_CHOICES = [(i, str(i)) for i in range(4)]
    THAL_CHOICES = [(3, 'Normal'), (6, 'Fixed defect'), (7, 'Reversible defect')]

    date = models.DateField()
    record_id = models.AutoField(primary_key=True)
    patient_id = models.ForeignKey('Patients', on_delete=models.CASCADE)
    age = models.IntegerField(validators=[MinValueValidator(20), MaxValueValidator(80)])
    sex = models.IntegerField(choices=SEX_CHOICES)
    chest_pain = models.IntegerField(choices=CP_CHOICES)
    blood_pressure = models.IntegerField(validators=[MinValueValidator(90), MaxValueValidator(200)])
    fasting_bs = models.IntegerField(choices=FASTING_CHOICES)
    resting_ecg= models.IntegerField(choices=RESTECG_CHOICES)
    exercise_angina = models.IntegerField(choices=EXE_ANGINA_CHOICES)
    cholesterol = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(500)])
    heart_rate = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(300)])
    st_depression = models.FloatField(validators=[MinValueValidator(0), MaxValueValidator(10)])
    slope = models.IntegerField(choices=SLOPE_CHOICES)
    vessels = models.IntegerField(choices= VESSELS_CHOICES)
    thal = models.IntegerField(choices=THAL_CHOICES)
    remarks = models.TextField(blank=True, null=True)


# Model for the prediction of the Medical Records
class PredictionResults(models.Model):
    prediction_id = models.AutoField(primary_key=True)
    record_id = models.ForeignKey('MedicalRecords', on_delete=models.CASCADE)
    prediction_result = models.CharField(max_length=10)
    risk_probability = models.FloatField(default=0.0)

Assignment_5/django_code/myapp/forms.py
from django import forms
from .models import  MedicalRecords
from django.core.validators import MinValueValidator, MaxValueValidator

# class HeartDisease(forms.ModelForm):


# Medical Records form
class MedicalRecordsForm(forms.ModelForm):
    class Meta:
        model = MedicalRecords
        fields = [
            'date', 'patient_id', 'age', 'sex', 'chest_pain', 'blood_pressure', 'fasting_bs',
            'resting_ecg', 'exercise_angina', 'cholesterol', 'heart_rate', 'st_depression',
            'slope', 'vessels', 'thal', 'remarks']
        widgets = {
            'date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'patient_id': forms.Select(attrs={'class': 'form-control'}),
            'age': forms.NumberInput(attrs={'class': 'form-control', 'min': '20', 'max': '80'}),
            'sex': forms.Select(attrs={'class': 'form-select'}),
            'chest_pain': forms.Select(attrs={'class': 'form-select'}),
            'blood_pressure': forms.NumberInput(attrs={'class': 'form-control', 'min': '90', 'max': '200'}),
            'fasting_bs': forms.Select(attrs={'class': 'form-select'}),
            'resting_ecg': forms.Select(attrs={'class': 'form-select'}),
            'exercise_angina': forms.Select(attrs={'class': 'form-select'}),
            'cholesterol': forms.NumberInput(attrs={'class': 'form-control', 'min': '0', 'max': '500'}),
            'heart_rate': forms.NumberInput(attrs={'class': 'form-control', 'min': '0', 'max': '300'}),
            'st_depression': forms.NumberInput(attrs={'class': 'form-control', 'min': '0', 'max': '10'}),
            'slope': forms.Select(attrs={'class': 'form-select'}),
            'vessels': forms.Select(attrs={'class': 'form-select'}),
            'thal': forms.Select(attrs={'class': 'form-select'}),
            'remarks': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
        }

        labels = {
            'date': 'Date of Test',
            'patient_id': 'Patient ID',
            'age': 'Age',
            'sex': 'Sex',
            'chest_pain': 'Chest pain type',
            'blood_pressure': 'Resting blood pressure',
            'fasting_bs': 'Fasting blood sugar',
            'resting_ecg': 'Resting electrocardiographic results',
            'exercise_angina': 'Exercise induced angina',
            'cholesterol': 'Serum cholesterol',
            'heart_rate': 'Maximum heart rate achieved',
            'st_depression': 'ST depression induced by exercise relative to rest',
            'slope': 'Slope of the peak exercise ST segment',
            'vessels': 'Number of major vessels colored by flourosopy',
            'thal': 'Thalassemia',
            'remarks': 'Remarks',
        }
    

Assignment_5/django_code/myapp/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404,reverse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

from .models import  MedicalRecords,PredictionResults, Patients
from .forms import  MedicalRecordsForm

import joblib
import numpy as np
model = joblib.load('model/model_heart.pkl')



def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('process_form') 
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('login') 

@login_required
def home(request):
    return render(request, "home.html")

def process_form(request):
    if request.method == 'POST':
        form = MedicalRecordsForm(request.POST)
        if form.is_valid():
            medical_record = form.save()

            data_for_prediction = preprocess_data(medical_record)
            print(data_for_prediction)

            prediction = model.predict(np.array(list(data_for_prediction.values())).reshape(1, -1))
            print(prediction)
            
            if prediction == 1:
                print('Heart ❤️ disease - Unlikely')
                prediction_risk = 'no risk'
            else:
                print('Heart 💔 disease - Likely.')
                prediction_risk = 'risk'
            
            risk_prob = model.predict_proba(np.array(list(data_for_prediction.values())).reshape(1, -1))[0][1]

            save_prediction_result(medical_record, prediction_risk,risk_prob)

            prediction_list = prediction.tolist()

            return JsonResponse({'prediction': prediction_list})
    else:
        form = MedicalRecordsForm()

    return render(request, 'heart_status.html', {'form': form})

# preprocessing data 
def preprocess_data(medical_record):
    data_for_prediction = {
        'age': medical_record.age,
        'sex': medical_record.sex,
        'chest_pain': medical_record.chest_pain,
        'blood_pressure': medical_record.blood_pressure,
        'fasting_bs' : medical_record.fasting_bs,
        'resting_ecg' : medical_record.resting_ecg,
        'exercise_angina' : medical_record.exercise_angina,
        'cholesterol' : medical_record.cholesterol,
        'heart_rate' : medical_record.heart_rate,
        'st_depression' : medical_record.st_depression,
        'slope' : medical_record.slope,
        'vessels' : medical_record.vessels,
        'thal' : medical_record.thal
        }
    return data_for_prediction

def save_prediction_result(medical_record, prediction,risk_probability):
    PredictionResults.objects.create(
        record_id=medical_record,
        prediction_result=prediction,
        risk_probability=risk_probability
    )

def patient_list(request):
    patients = Patients.objects.all()
    return render(request, 'patient_list.html', {'patients': patients})

def medical_records_list(request):
    medical_records = MedicalRecords.objects.all()
    return render(request, 'medical_records_list.html', {'medical_records': medical_records})


def prediction_results_list(request):
    prediction_results = PredictionResults.objects.all()
    return render(request, 'prediction_results_list.html', {'prediction_results': prediction_results})

def about_page(request):
    return render(request, 'about.html')

def technical_support(request):
    return render(request, 'technical_support.html')

Assignment_5/django_code/myapp/templates/about.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <h2 class="mb-4">About HeartHealth Pro</h2>
        <p class="lead">Welcome to HeartHealth Pro, your go-to tool for cardiovascular risk assessment.</p>
        <p>Our cardiovascular risk prediction application utilizes cutting-edge machine learning algorithms to assist healthcare professionals in evaluating the likelihood of heart disease in their patients. By analyzing a comprehensive set of health and clinical indicators, our app serves as an invaluable early diagnosis tool, enabling the identification of individuals at risk of developing heart disease.</p>
        <p>Designed specifically for healthcare professionals, HeartHealth Pro is an indispensable asset in promoting cardiovascular health and preventing heart disease. With its intuitive interface and precise risk assessments, our application facilitates seamless patient evaluation and management, empowering healthcare providers to deliver optimal care.</p>
        <p>Whether you're a physician, nurse, or allied healthcare professional, HeartHealth Pro equips you with the insights needed to deliver personalized care and intervention strategies. By proactively identifying individuals at risk of heart disease, you can initiate timely interventions and safeguard their heart health, ultimately enhancing their overall well-being.</p>
      </div>
    </div>
  </div>
{% endblock %}

Assignment_5/django_code/myapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Heart Disease Risk Predictor
        {% endblock %}
    </title>
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

    
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="{% url 'process_form' %}">HeartHealth Pro</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mx-auto"> 
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'process_form' %}">Home</a>
                </li>
                <li class="nav-item dropdown"> 
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      DataView
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'patient_list' %}">Patients</a></li>
                    <li><a class="dropdown-item" href="{% url 'medical_records_list' %}">Medical Records</a></li>
                    <li><a class="dropdown-item" href="{% url 'prediction_results_list' %}">Prediction Results</a></li>
                  </ul>
              </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'technical_support' %}">Support</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto"> 
                <li class="nav-item">
                    <a class="nav-link" href="#">🟢</a> 
                </li>
                <li class="nav-item">
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link nav-link">Logout</button>
                    </form>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container mt-4">
    {% block content %}
    {% endblock %}
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Assignment_5/django_code/myapp/templates/heart_status.html
{% extends "base.html" %}
{% block title %} Home Page {% endblock %}

{% block content %}
<div class="container">
    <form id="medical-record-form" method="POST">
        {% csrf_token %}
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.date.label_tag }}
                {{ form.date }}
            </div>
            <div class="col-md-6">
                {{ form.patient_id.label_tag }}
                {{ form.patient_id }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.age.label_tag }}
                {{ form.age }}
            </div>
            <div class="col-md-6">
                {{ form.sex.label_tag }}
                {{ form.sex }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.chest_pain.label_tag }}
                {{ form.chest_pain }}
            </div>
            <div class="col-md-6">
                {{ form.blood_pressure.label_tag }}
                {{ form.blood_pressure }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.fasting_bs.label_tag }}
                {{ form.fasting_bs }}
            </div>
            <div class="col-md-6">
                {{ form.resting_ecg.label_tag }}
                {{ form.resting_ecg }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.exercise_angina.label_tag }}
                {{ form.exercise_angina }}
            </div>
            <div class="col-md-6">
                {{ form.cholesterol.label_tag }}
                {{ form.cholesterol }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.heart_rate.label_tag }}
                {{ form.heart_rate }}
            </div>
            <div class="col-md-6">
                {{ form.st_depression.label_tag }}
                {{ form.st_depression }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.slope.label_tag }}
                {{ form.slope }}
            </div>
            <div class="col-md-6">
                {{ form.vessels.label_tag }}
                {{ form.vessels }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.thal.label_tag }}
                {{ form.thal }}
            </div>
            <div class="col-md-6">
                {{ form.remarks.label_tag }}
                {{ form.remarks }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                <button type="submit" class="btn btn-primary col-md-12">Submit</button>
            </div>
            <div class="col-md-6">
                <button type="reset" class="btn btn-secondary col-md-12">Reset</button>
            </div>
        </div>      
    </form>
    <div id="prediction-outcome" class="mt-3">
        <p id="prediction-message"></p>
    </div>
</div>

<script>
    document.getElementById('medical-record-form').addEventListener('submit', function(event) {
        event.preventDefault(); // Prevent default form submission

        // Serialize form data
        const formData = new FormData(event.target);

        // Send form data to server using fetch API
        fetch('{% url 'process_form' %}', {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            }
        })
        .then(response => response.json())
        .then(data => {
            // Update prediction outcome message
            const predictionOutcome = document.getElementById('prediction-message');
            if (parseInt(data.prediction[0]) === 1) {
                predictionOutcome.textContent = 'Heart disease - Unlikely.';
                predictionOutcome.style.color = 'green';
            } else {
                predictionOutcome.textContent = 'Heart disease - Likely!';
                predictionOutcome.style.color = 'red';
            }

            // Reset form fields
            document.getElementById('medical-record-form').reset();
        })
        .catch(error => {
            console.error('Error:', error);
        });
    });
</script>
{% endblock %}

Assignment_5/django_code/myapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cardio Disease Predictor Login</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f8f9fa;
        }

        .login-container {
            width: 350px;
            padding: 20px;
            border: 1px solid #ced4da;
            border-radius: 8px;
            background-color: #fff;
            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
        }

        .login-container h2 {
            text-align: center;
            margin-bottom: 20px;
        }

        .app-name {
            text-align: center;
            margin-bottom: 20px;
            font-size: 24px;
            color: #333; /* Adjust color as needed */
        }
    </style>
</head>
<body>
    <div class="login-container">
        <div class="app-name">HeartHealth Pro</div>
        <h2>Login</h2>
        <form method="post" class="needs-validation" novalidate>
            {% csrf_token %}
            <!-- Username field -->
            <div class="mb-3">
                <label for="id_username" class="form-label">Username</label>
                {{ form.username }}
                
                <div class="invalid-feedback">{{ form.username.errors }}</div>
            </div>
            <!-- Password field -->
            <div class="mb-3">
                <label for="id_password" class="form-label">Password</label>
                {{ form.password }}
                
                <div class="invalid-feedback">{{ form.password.errors }}</div>
            </div>
            <!-- Submit button -->
            <button type="submit" class="btn btn-primary btn-block">Login</button>
        </form>
    </div>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Assignment_5/django_code/myapp/templates/medical_records_list.html
<!-- medical_records_list.html -->
{% extends "base.html" %}
{% block title %}
    Medical Records List - HeartHealth Pro
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Medical Records List</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Record ID</th>
                <th>Date</th>
                <th>Patient ID</th>
                <th>Age</th>
                <th>Sex</th>
                <th>Chest Pain</th>
                <th>Blood Pressure</th>
                <th>Fasting BS</th>
                <th>Resting ECG</th>
                <th>Exercise Angina</th>
                <th>Cholesterol</th>
                <th>Heart Rate</th>
                <th>ST Depression</th>
                <th>Slope</th>
                <th>Vessels</th>
                <th>Thal</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            {% for record in medical_records %}
            <tr>
                <td>{{ record.record_id }}</td>
                <td>{{ record.date }}</td>
                <td>{{ record.patient_id }}</td>
                <td>{{ record.age }}</td>
                <td>{{ record.get_sex_display }}</td>
                <td>{{ record.get_chest_pain_display }}</td>
                <td>{{ record.blood_pressure }}</td>
                <td>{{ record.get_fasting_bs_display }}</td>
                <td>{{ record.get_resting_ecg_display }}</td>
                <td>{{ record.get_exercise_angina_display }}</td>
                <td>{{ record.cholesterol }}</td>
                <td>{{ record.heart_rate }}</td>
                <td>{{ record.st_depression }}</td>
                <td>{{ record.get_slope_display }}</td>
                <td>{{ record.vessels }}</td>
                <td>{{ record.get_thal_display }}</td>
                <td>{{ record.remarks }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

Assignment_5/django_code/myapp/templates/patient_list.html
{% extends "base.html" %}
{% block title %}
    Patient List - HeartHealth Pro
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Patient List</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Patient ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Date of Birth</th>
                <th>Sex</th>
                <th>Height</th>
                <th>Weight</th>
                <th>Blood Type</th>
                <th>City</th>
                <th>Street</th>
                <th>Telephone Number</th>
                <th>Insurance Number</th>
            </tr>
        </thead>
        <tbody>
            {% for patient in patients %}
            <tr>
                <td>{{ patient.patient_id }}</td>
                <td>{{ patient.first_name }}</td>
                <td>{{ patient.last_name }}</td>
                <td>{{ patient.date_of_birth }}</td>
                <td>{{ patient.sex }}</td>
                <td>{{ patient.height }}</td>
                <td>{{ patient.weight }}</td>
                <td>{{ patient.blood_type }}</td>
                <td>{{ patient.city }}</td>
                <td>{{ patient.street }}</td>
                <td>{{ patient.telephone_number }}</td>
                <td>{{ patient.insurance_number }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

Assignment_5/django_code/myapp/templates/prediction_results_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Prediction Results - HeartHealth Pro
{% endblock %}

{% block content %}
    <h1>Prediction Results</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Prediction ID</th>
                <th scope="col">Record ID</th>
                <th scope="col">Prediction Result</th>
                <th scope="col">Risk Probability</th>
            </tr>
        </thead>
        <tbody>
            {% for prediction_result in prediction_results %}
            <tr>
                <td>{{ prediction_result.prediction_id }}</td>
                <td>{{ prediction_result.record_id }}</td>
                <td>{{ prediction_result.prediction_result }}</td>
                <td>{{ prediction_result.risk_probability }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

Assignment_5/django_code/myapp/templates/technical_support.html
<!-- technical_support.html -->

{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
  <h2 class="mb-4">Welcome to the Technical Support</h2>
  <p>In this section, you will find a range of resources to help you get the most out of our app.</p>

  <h3 class="mb-4">User Manual:</h3>
  <p>Our user manual provides detailed instructions on how to use our app, including step-by-step guides and troubleshooting tips. If you have any questions about how to use our app, please consult the user manual for assistance.</p>

  <h3 class="mb-4">Reading Resources:</h3>
  <p>In addition to our user manual, we also provide a range of reading resources to help you understand more about cardiovascular health and the risk factors associated with heart disease. These resources include articles, studies, and other educational materials that can help you make informed decisions about your heart health.</p>

  <h3 class="mb-4">Model Clarification:</h3>
  <p>Our app uses a machine learning algorithm to predict the likelihood of heart disease based on various health and clinical indicators. The model has been trained on a large dataset of patient records and has been validated for accuracy. However, it is important to note that no prediction model is perfect, and our app should be used as a tool to assist healthcare professionals in their assessment of a patient's heart health, rather than as a substitute for medical advice.</p>

  <p>If you have any technical issues or questions about our app, please don't hesitate to contact our support team. We are here to help you get the most out of our cardiovascular risk prediction application.</p>
</div>
  </div>
</div>
{% endblock %}